#!/usr/bin/bash
#
# The kk system needs only 1 file: kkcmd

export KKDIR=${KKDIR:-$HOME/.kkdir}

# cd to an entry
kk() {
  t1=`kkcmd -c $1`
  echo "cd $t1"
  cd $t1
}

# assign an entry
kka() {
  kkcmd $*
}

kkl() {
  kkcmd -l $*
}

# delete an entry
kkd() {
  kkcmd -d $1
}

# assign shell variables
kkv() {
  kkcmd -v $* 
  . $KKDIR/temp_k2
}

# unset shell variables. Not implemented yet.
kku() {
  kkcmd -u $*
  . $KKDIR/temp_k2
}

# list grep entries
kkg() {
  if [ $# -ge 1 ]; then
    grep -i --color=always $1 $KKDIR/temp_k
  fi
}

# edit entries
alias kke="vi $KKDIR/temp_k"


